<?

$prd_search = "
<table border=0 cellpadding=2 cellspacing=0>
<form action='/shop/prd_search.php'>
<tr><td><img src='/images/mainimg/search_01.gif'></td>
	<td><input type='text' name='prdname' style='width:150' class='input'></td>
	<td><input type='image' src='/images/mainimg/search_btn.gif' border=0></a></td>
	<td><a href='/shop/prd_search.php'><img src='/images/mainimg/search_btn_detail.gif' border=0></a></td></tr>
</form>
</table>";

?>