                                                  <? if($webedit_height == "") $webedit_height = 300; ?>
                                                  <tr> 
                                                    <td width="150" height="25" align="left" bgcolor="EAEAEA">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$webedit_title?></td>
                                                    <td width="550" bgcolor="F8F8F8" colspan="3">
                                                      <table id="tblCtrls" width="100%" border="0" cellspacing="1" cellpadding="0" align="center">
																        <tr> 
																          <td bgcolor="F5F6F5">
																			 	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																              <tr> 
																                <td width="18%" height="56">
																					 	<table width="100%" height="56" border="0" align="center" cellpadding="0" cellspacing="0">
																                    <tr align="center" valign="bottom"> 
																                      <td height="26"><a href="javascript:doBold();" onMouseOver="MM_swapImage('Image1','','../webedit/image/wtool1_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool1.gif" name="Image1" width="19" height="18" border="0" id="Image1"></a></td>
																                      <td><a href="javascript:doItalic();" onMouseOver="MM_swapImage('Image2','','../webedit/image/wtool2_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool2.gif" name="Image2" width="19" height="18" border="0" id="Image2"></a></td>
																                      <td><a href="javascript:doUnderline();" onMouseOver="MM_swapImage('Image3','','../webedit/image/wtool3_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool3.gif" name="Image3" width="19" height="18" border="0" id="Image3"></a></td>
																                    </tr>
																                    <tr> 
																                      <td height="3" colspan="3"></td>
																                    </tr>
																                    <tr align="center" valign="top"> 
																                      <td height="27"><a href="javascript:doLeft();" onMouseOver="MM_swapImage('Image8','','../webedit/image/wtool8_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool8.gif" name="Image8" width="19" height="18" border="0" id="Image8"></a></td>
																                      <td><a href="javascript:doCenter();" onMouseOver="MM_swapImage('Image9','','../webedit/image/wtool9_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool9.gif" name="Image9" width="19" height="18" border="0" id="Image9"></a></td>
																                      <td><a href="javascript:doRight();" onMouseOver="MM_swapImage('Image10','','../webedit/image/wtool10_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool10.gif" name="Image10" width="19" height="18" border="0" id="Image10"></a></td>
																                    </tr>
																                  </table>
																					 </td>
																                <td width="2"><img src="../webedit/image/bar.gif" width="2" height="39" align="absmiddle"></td>
																                <td width="19%">
																					 	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																                    <tr> 
																                      <td width="100%" height="27" align="center" valign="bottom"><a href="javascript:doFont();" onMouseOver="MM_swapImage('Image4','','../webedit/image/wtool4_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool4.gif" name="Image4" width="84" height="22" border="0" id="Image4"></a></td>
																                    </tr>
																                    <tr>
																                      <td height="2"></td>
																                    </tr>
																                    <tr> 
																                      <td height="27" align="center" valign="top"><a href="javascript:doSize();" onMouseOver="MM_swapImage('Image11','','../webedit/image/wtool11_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool11.gif" name="Image11" width="84" height="22" border="0" id="Image11"></a></td>
																                    </tr>
																                  </table>
																					 </td>
																                <td width="2"><img src="../webedit/image/bar.gif" width="2" height="39" align="absmiddle"></td>
																                <td width="20%">
																					 	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																                    <tr> 
																                      <td height="27" align="center" valign="bottom"><a href="javascript:doForcol();" onMouseOver="MM_swapImage('Image5','','../webedit/image/wtool5_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool5.gif" name="Image5" width="95" height="22" border="0" id="Image5"></a></td>
																                    </tr>
																                    <tr> 
																                      <td height="2"></td>
																                    </tr>
																                    <tr> 
																                      <td height="27" align="center" valign="top"><a href="javascript:doBgcol();" onMouseOver="MM_swapImage('Image12','','../webedit/image/wtool12_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool12.gif" name="Image12" width="95" height="22" border="0" id="Image12"></a></td>
																                    </tr>
																                  </table>
																					 </td>
																                <td width="2"><img src="../webedit/image/bar.gif" width="2" height="39" align="absmiddle"></td>
																                <td width="18%">
																					 	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																                    <tr> 
																                      <td height="27" align="center" valign="bottom"><a href="javascript:doImage();" onMouseOver="MM_swapImage('Image6','','../webedit/image/wtool6_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool6.gif" name="Image6" width="73" height="22" border="0" id="Image6"></a></td>
																                    </tr>
																                    <tr> 
																                      <td height="2"></td>
																                    </tr>
																                    <tr> 
																                      <td height="27" align="center" valign="top"><a href="javascript:doTable();" onMouseOver="MM_swapImage('Image13','','../webedit/image/wtool13_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool13.gif" name="Image13" width="73" height="22" border="0" id="Image13"></a></td>
																                    </tr>
																                  </table>
																					 </td>
																                <td width="2"><img src="../webedit/image/bar.gif" width="2" height="39" align="absmiddle"></td>
																                <td width="25%">
																					 	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																                    <tr> 
																                      <td height="27" align="center" valign="bottom"><a href="javascript:doLink();" onMouseOver="MM_swapImage('Image7','','../webedit/image/wtool7_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool7.gif" name="Image7" width="74" height="22" border="0" id="Image7"></a></td>
																                    </tr>
																                    <tr> 
																                      <td height="2"></td>
																                    </tr>
																                    <tr> 
																                      <td height="27" align="center" valign="top"><a href="javascript:doMultilink();" onMouseOver="MM_swapImage('Image14','','../webedit/image/wtool14_1.gif',1)" onMouseOut="MM_swapImgRestore()"><img src="../webedit/image/wtool14.gif" name="Image14" width="111" height="22" border="0" id="Image14"></a></td>
																                    </tr>
																                  </table>
																					 </td>
																              </tr>
																            </table>
																			 </td>
																        </tr>
																      </table>
                                                    </td>
                                                  </tr>
                                                  <tr> 
                                                    <td width="100%" bgcolor="F8F8F8" colspan="4" align="center">
                                                    <iframe align="right" id="iView" style="width: 99.5%; height:<?=$webedit_height?>;" scrolling='YES' hspace="0" vspace="0"></iframe>
                                                    </td>
                                                  </tr>
                                                  <tr> 
                                                    <td width="100%" bgcolor="F8F8F8" colspan="4" align="right">
                                                    <input type="checkbox" name="toggle" onClick="doToggle();">htmlÆíÁý
                                                    </td>
                                                  </tr>