						</td>
                    </tr>

                  </table>

                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td>
                        <?php require_once('../include/footer.php');?>
                      </td>
                    </tr>
                  </table></td>
              </tr>
            </table>
            <map name="Map11Map" id="Map112">
              <area shape="rect" coords="2,2,97,187" href="#">
              <area shape="rect" coords="2,191,96,374" href="#">
            </map>

		</td>
          <td align="right" valign="top"><table width="69" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><?php require_once('../include/quick.php');?></td>
              </tr>
            </table></td>
        </tr>
      </table>
      
    </td>
  </tr>
</table>

</body>
</html>
