<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<? //include "../include/meta.inc"; ?>
<title><?=$design_info->site_title?></title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<meta name="keywords" content="<?=$design_info->site_keyword?>">
<meta name="description" content="<?=$design_info->site_intro?>">
<link href="../css/css.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</script>
</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <!--td height="146" align="center" valign="top" background="/img/top_bg.gif"--><td height="146" valign="top" background="/img/top_bg.gif" style="padding:0 0 0 20"><table width="1030" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="950"><table width="950" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td>
                  <?php require_once('../include/top_menu.php');?>
                </td>
              </tr>
            </table></td>
          <td>&nbsp;</td>
        </tr>
      </table>
      
    </td>
  </tr>
  <tr>
    <!--td align="center" style="padding:10 0 0 0"--><td style="padding:10 0 0 20"><table width="1030" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="950"><table width="950" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td>
				
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td width="184" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td>
                              <?php require_once('../include/left_menu.php');?>
                            </td>
                          </tr>
                        </table></td>
                      <td width="803" valign="top" style="padding:0 0 0 10">
