<table border=0 cellpadding=0 cellspacing=0 width=900>
  <tr>
    <td background="/images/mainimg/body_bg.gif" align=center>

		<table border=0 cellpadding=0 cellspacing=0 width=900>
		  <tr>
		    <td width=180 height=50><?=$logo?></td>
			 <td align=right><?=$top_navi?></td>
			 <td align=right style="padding:0 10 0 0"><?=$prd_search?></td>
	     </tr>
		</table>
    </td>
  </tr>
  <tr>
    <td background="/images/mainimg/body_bg.gif"><?=$top_menu?></td>
  </tr>
  <tr>
    <td background="/images/mainimg/body_bg.gif" style="padding:4 0 0 0">
      <table border=0 cellpadding=0 cellspacing=0 width=100%>
        <tr>
          <td width=180 style="padding:0 0 10 0" valign=top>
  
				<table border=0 cellpadding=0 cellspacing=0 width=100%>
				  <tr>
				    <td><?=$category?></td>
				  </tr>
				  <tr height=10><td></td></tr>
				  <tr>
				    <td><?=$left_banner?></td>
				  </tr>
				</table>
          </td>
          <td background="/images/mainimg/mid_bg.gif" style="padding:0 0 10 0" valign=top>