<table border=0 cellpadding=0 cellspacing=0 width=100%>
  <tr>
    <td>
	   <table border=0 cellpadding=0 cellspacing=0 width=100%> 
	     <tr>
		   <td><?=$main_img?></td>
			<td valign=top>
				<table border=0 cellpadding=0 cellspacing=0 width=252>
				  <tr>
				    <td><?=$notice?></td>
				  </tr>
				  <tr><td height=8></td>
				  <tr>
				    <td><?=$right_banner?></td>
				</table>
			</td>
	    </tr>
	  </table>
    </td>
  </tr>
  <tr>
    <td valign=top><?=$main_product?></td>
  </tr>
</table>