                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td><img src="../image/tit01_left.gif" width="187" height="74"></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td height="28" background="../image/category_bg.gif"><table width="187" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td width="25"><img src="../image/mark_category.gif" width="25" height="9"></td>
                            <td>
                              <strong><font color="2E2E2E"><a href="./shop_info.php" class="1">커뮤니티관리 </a></font></strong></td>
                          </tr>
                        </table></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td align="center" valign="top"><table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="../bbs/bbs_pro_list.php" class="1">게시판목록</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="../bbs/bbs_list.php" class="1">게시물관리</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="../bbs/bbs_list.php?code=notice" class="1">공지사항</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="../bbs/bbs_list.php?code=faq" class="1">자주하는질문</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <!--
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="../bbs/bbs_list.php" class="1">설문조사</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        -->
                        </td>
                    </tr>
                  </table>
                  <table width="187" height="10" border="0" cellpadding="0" cellspacing="0">
                    <tr> 
                      <td></td>
                    </tr>
                  </table>
                  <? include "../inc/sys_info.inc"; ?>