                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td><img src="../image/tit01_left.gif" width="187" height="74"></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td height="28" background="../image/category_bg.gif"><table width="187" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td width="25"><img src="../image/mark_category.gif" width="25" height="9"></td>
                            <td>
                              <strong><font color="2E2E2E"><a href="./shop_info.php" class="1">디자인관리 </a></font></strong></td>
                          </tr>
                        </table></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td align="center" valign="top">
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_basic.php" class="1">디자인기본설정</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_layout.php" class="1">레이아웃구성</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_mainlayout.php" class="1">메인화면구성</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_main.php" class="1">디자인상세설정</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <br>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_popup.php" class="1">팝업관리</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_banner.php" class="1">배너관리</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_content_list.php" class="1">페이지추가</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./dsn_webftp.php" class="1">WEB-FTP</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        </td>
                    </tr>
                  </table>
                  <table width="187" height="10" border="0" cellpadding="0" cellspacing="0">
                    <tr> 
                      <td></td>
                    </tr>
                  </table>
                  <? include "../inc/sys_info.inc"; ?>