                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td><img src="../image/tit01_left.gif" width="187" height="74"></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td height="28" background="../image/category_bg.gif"><table width="187" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td width="25"><img src="../image/mark_category.gif" width="25" height="9"></td>
                            <td>
                              <strong><font color="2E2E2E"><a href="./shop_info.php" class="1">마케팅분석 </a></font></strong></td>
                          </tr>
                        </table></td>
                    </tr>
                  </table>
                  <table width="187" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      <td align="center" valign="top"><table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./connect_list.php" class="1">접속자분석</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./connect_refer.php" class="1">접속경로분석</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./analy_paymethod.php" class="1">매출통계분석</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./analy_prd.php" class="1">상품통계분석</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        <!--
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./shop_oper.php" class="1">wish list 통계</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        -->
                        <table width="140" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td height="26"><a href="./analy_member.php" class="1">회원통계</a></td>
                          </tr>
                        </table>
                        <table width="164" height="1" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <td bgcolor="E4E4E4"></td>
                          </tr>
                        </table>
                        
                        </td>
                    </tr>
                  </table>
                  <table width="187" height="10" border="0" cellpadding="0" cellspacing="0">
                    <tr> 
                      <td></td>
                    </tr>
                  </table>
                  <? include "../inc/sys_info.inc"; ?>