                  <table width="165" border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr> 
                      <td bgcolor="E5E5E5"><table width="165" border="0" cellspacing="1" cellpadding="0">
                          <tr> 
                            <td align="center" valign="top" bgcolor="#FFFFFF">
                              <table width="163" height="7" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <td></td>
                                </tr>
                              </table>
                              <table width="153" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td><img src="../image/img_system.gif" width="153" height="47"></td>
                                </tr>
                              </table>
                              <table width="142" height="5" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <td></td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="57" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    상품수 </td>
                                  <td width="9">:</td>
                                  <td width="65" align="right"><font color="1A61B0"><?=$prd_total?></font>개</td>
                                  <td width="11">&nbsp;</td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="57" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    HDD </td>
                                  <td width="9">:</td>
                                  <td width="65" align="right"><font color="1A61B0"><?=$disk_use?></font>MB</td>
                                  <td width="11">&nbsp;</td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="57" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    DB </td>
                                  <td width="9">:</td>
                                  <td width="65" align="right"><font color="1A61B0"><?=$db_total?></font>MB</td>
                                  <td width="11">&nbsp;</td>
                                </tr>
                              </table>
                              <table width="142" height="5" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <td></td>
                                </tr>
                              </table>
                              <table width="153" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td><img src="../image/img_loginer.gif" width="153" height="47"></td>
                                </tr>
                              </table>
                              <table width="142" height="5" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <td></td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="80" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    현재접속자</td>
                                  <td width="8">:</td>
                                  <td width="46" align="right"><font color="F42189"><?=$now_cnt?>명</font></td>
                                  <td width="8"></td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="80" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    오늘방문자</td>
                                  <td width="8">:</td>
                                  <td width="46" align="right"><font color="1A61B0"><?=$today_cnt?>명</font></td>
                                  <td width="8"></td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="80" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    어제방문자</td>
                                  <td width="8">:</td>
                                  <td width="46" align="right"> <?=$yester_cnt?>명</td>
                                  <td width="8"></td>
                                </tr>
                              </table>
                              <table width="142" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td width="80" height="22"><img src="../image/mark_dotblue.gif" width="7" height="7" align="absmiddle"> 
                                    총방문자 </td>
                                  <td width="8">:</td>
                                  <td width="46" align="right"><?=$total_cnt?>명</td>
                                  <td width="8"></td>
                                </tr>
                              </table>
                              <table width="142" height="5" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <td></td>
                                </tr>
                              </table></td>
                          </tr>
                        </table>
                        </td>
                    </tr>
                  </table>